### PR TITLE
Update FSHQuickReference.pdf

### PR DESCRIPTION
**Pull request by markkramerus**
Please carefully check -- especially recently-changed and added areas.

### CODE REVIEW

**Comment by markkramerus** [comment]
It looks like Description is required in Invariant, right?  If this is mapped to ElementDefinition.constraint.human?

**Comment by cmoesel** [comment]
> It looks like Description is required in Invariant, right? If this is mapped to ElementDefinition.constraint.human?

Ah, yes!  You got me there!

**Comment by markkramerus** [comment]
New file uploaded. Thanks for the review!

**Comment by cmoesel** [comment]
Looking good!  I can't believe you fit all that in.  Just a few more things...

PAGE 1:

* **Keywords**: Does italicized keyword mean optional?  If so, then shouldn't Mixins be italicized in all those?
* **Keywords->Profile and Extension**: Since you combined these, should Parent say `profile or extension or resource or url`?
* **Keywords->Value set and Code System**: Inconsistent casing: `set` is lowercase and `System` is uppercase.
* **Rules->Binding**: The code one says `binding strength` but the quantity one says `bind. strength`.  Is this because `binding strength` wouldn't fit? If so, do you think just `strength` would do (so they can be consistent)? This is already in the context of binding, so I think that's fair.

**Comment by markkramerus** [comment]
> Does italicized keyword mean optional? If so, then shouldn't Mixins be italicized in all those?
Yes, it says so next to bold **Keywords**

**Pull request merged**
