### PR TITLE
Remove TU markings from Language Reference

### PR DESCRIPTION
**Pull request by jafeltra**
This PR removes all TU marking from the FSH Language Reference. All the support for adding TU and the appropriate background color to sections and table rows/columns are left in for any future TU features we may have.

I also made some very small styling adjustments to Table 10 and Table 12, but I can easily revert those if we don't like them.

### CODE REVIEW

**Comment by cmoesel** [comment]
You did exactly what I asked for, but now I'm wondering... Do we need to keep the R5-related changes (like CodeableReference and integer64) marked as TU since they are TU in R5? @markkramerus, what do you think?

**Review by markkramerus — CHANGES_REQUESTED** [review]
A couple of things:
1) There is a TU on the Overview page that should be removed.
2) Double check the status of integer64 and CodeableReference in FHIR -- Chris said yesterday that TU markings were removed. If so, we can remove the TU from the FSH spec, also. So potentially you might need to back out your latest commit. 

Otherwise, great job!

**Comment by cmoesel** [comment]
@markkramerus - I was wrong before. I didn't see `CodeableReference` or `integer64` marked as TU, so I assumed they were not TU. But that was wrong. As it turns out, according to [this page](https://hl7.org/fhir/2022Sep/ballot-intro.html), everything in R5 is trial-use.
image

**Comment by cmoesel** [comment]
@markkramerus - I was wrong before. I didn't see `CodeableReference` or `integer64` marked as TU, so I assumed they were not TU. But that was wrong. As it turns out, according to [this page](https://hl7.org/fhir/2022Sep/ballot-intro.html), everything in R5 is trial-use.
image

**Comment by jafeltra** [comment]
@markkramerus - I just updated the PR to remove the TU on the Overview page -- thanks for catching that one I completely missed. I also updated the version to `3.0.0-ballot`.

**Review by markkramerus — APPROVED** [review]

**Pull request merged**
